import { ExerciseEdgeSchema, skillRank, type Exercise, type ExerciseEdge, type MovementPattern } from '@fitadapt/shared';
import { SIMILARITY_CONFIG } from './config.js';
import type { Ladder } from './seed/ladders.js';

export const EDGE_SOURCE = {
  ladder: 'M06 seed progression ladder (docs/specs/M02 variant ladders where named); author ordering, awaiting A3 review',
  similarity: 'Generated by the M06 stimulus-similarity model (src/config.ts, engineering defaults); awaiting A2/A3 review',
  requires: 'M06 seed equipment requirement; awaiting A3 review',
} as const;

/** Patterns whose exercises may substitute each other across patterns when muscles match closely. */
const STRENGTH_PATTERNS: ReadonlySet<MovementPattern> = new Set(['squat', 'hinge', 'lunge', 'horizontal_push', 'vertical_push', 'horizontal_pull', 'vertical_pull', 'carry', 'core', 'isolation']);

function jaccard<T>(a: readonly T[], b: readonly T[]): number {
  const sa = new Set(a);
  const sb = new Set(b);
  let inter = 0;
  for (const x of sa) if (sb.has(x)) inter++;
  const union = sa.size + sb.size - inter;
  return union === 0 ? 0 : inter / union;
}

/** Stimulus similarity of two exercises, 0–1, symmetric (see config.ts). */
export function stimulusSimilarity(a: Exercise, b: Exercise, config = SIMILARITY_CONFIG): number {
  const samePattern = a.pattern === b.pattern ? 1 : 0;
  const primary = jaccard(a.primaryMuscles, b.primaryMuscles);
  const all = jaccard([...a.primaryMuscles, ...a.secondaryMuscles], [...b.primaryMuscles, ...b.secondaryMuscles]);
  const laterality = a.unilateral === b.unilateral ? 1 : 0;
  const skill = 1 - Math.abs(skillRank(a.skill) - skillRank(b.skill)) / 4;
  const raw =
    config.weightPattern.value * samePattern +
    config.weightPrimaryMuscles.value * primary +
    config.weightAllMuscles.value * all +
    config.weightLaterality.value * laterality +
    config.weightSkill.value * skill;
  return Math.round(Math.min(1, Math.max(0, raw)) * 1000) / 1000;
}

/** Whether two exercises may be linked by a SUBSTITUTES edge at all. */
export function substitutable(a: Exercise, b: Exercise): boolean {
  if (a.id === b.id) return false;
  if (a.pattern === b.pattern) return true;
  return STRENGTH_PATTERNS.has(a.pattern) && STRENGTH_PATTERNS.has(b.pattern);
}

export function ladderEdges(ladders: readonly Ladder[]): ExerciseEdge[] {
  const edges: ExerciseEdge[] = [];
  const seen = new Set<string>();
  for (const ladder of ladders) {
    for (let i = 0; i + 1 < ladder.steps.length; i++) {
      for (const from of ladder.steps[i] ?? []) {
        for (const to of ladder.steps[i + 1] ?? []) {
          const key = `${from}>${to}`;
          if (seen.has(key)) continue;
          seen.add(key);
          edges.push({ type: 'PROGRESSES_TO', from, to, ladderId: ladder.id, source: EDGE_SOURCE.ladder, validated: false });
          edges.push({ type: 'REGRESSES_TO', from: to, to: from, ladderId: ladder.id, source: EDGE_SOURCE.ladder, validated: false });
        }
      }
    }
  }
  return edges;
}

export function substituteEdges(exercises: readonly Exercise[], config = SIMILARITY_CONFIG): ExerciseEdge[] {
  const edges: ExerciseEdge[] = [];
  for (const a of exercises) {
    for (const b of exercises) {
      if (!substitutable(a, b)) continue;
      const similarity = stimulusSimilarity(a, b, config);
      if (similarity >= config.minSimilarity.value) edges.push({ type: 'SUBSTITUTES', from: a.id, to: b.id, similarity, source: EDGE_SOURCE.similarity, validated: false });
    }
  }
  return edges;
}

export function requiresEdges(exercises: readonly Exercise[]): ExerciseEdge[] {
  return exercises.flatMap((e) =>
    e.equipment.flatMap((group, index) => group.anyOf.map((to): ExerciseEdge => ({ type: 'REQUIRES', from: e.id, to, group: index, source: EDGE_SOURCE.requires, validated: false }))),
  );
}

/** All typed edges of the graph, validated against the schema. */
export function buildEdges(exercises: readonly Exercise[], ladders: readonly Ladder[], config = SIMILARITY_CONFIG): ExerciseEdge[] {
  return [...ladderEdges(ladders), ...substituteEdges(exercises, config), ...requiresEdges(exercises)].map((e) => ExerciseEdgeSchema.parse(e));
}
