// @ts-check
/**
 * `pnpm legal:docs`: checks docs/legal (M20 goal condition 6) and keeps its
 * generated parts in sync with packages/legal: the draft texts
 * (docs/legal/drafts/*.md, rendered from packages/i18n), the jurisdiction
 * matrix and the counsel sign-off tracker. `--write` regenerates them.
 */
import { DEFAULT_REGISTRY, DOCUMENT_VARIANTS, JURISDICTION_MATRIX, NOTICES, renderDocument, renderNotice, resolveSection } from '@fitadapt/legal';
import { createTranslator } from '@fitadapt/i18n';
import { DRAFT_MARKER, FORBIDDEN_APPROVAL, tableRows } from './markdown.mjs';

export const LEGAL_DIR = 'docs/legal';
export const REQUIRED_DOCUMENTS = Object.freeze([
  'README.md',
  'founder-checklist.md',
  'jurisdiction-matrix.md',
  'risk-register.md',
  'document-list.md',
  'trademark-register.md',
  'incident-procedure.md',
  'counsel-signoff-tracker.md',
  'substantiation-file.md',
  'asset-licence-register.md',
  'defensibility-file.md',
  'drafts/coach-agreement.md',
  'drafts/advisory-board-agreement.md',
]);

/** Gate 0 items of docs/specs/00-legal-framework.md. */
export const GATE0_ITEMS = Object.freeze(['Company structure', 'IP ownership', 'Founder employment check', 'Counsel', 'Name clearance', 'Insurance', 'Advisory board', 'Data-protection filings']);
/** Risk-register domains of docs/specs/00-legal-framework.md. */
export const RISK_DOMAINS = Object.freeze([
  'Personal injury / negligence', 'Medical-device regulation', 'Regulated professions', 'Data protection', 'AI regulation and AI harm',
  'Consumer and subscription law', 'Misleading advertising', 'Copyright and licences', 'Trademark conflict', 'Third-party coaches',
  'User-generated content', 'Minors', 'Accessibility', 'Store policies', 'Founder personal exposure', 'Tax',
]);
export const INCIDENT_STEPS = Object.freeze(['Injury report', 'Escalation', 'Legal hold', 'Regulator notification', 'Insurer notification', 'Complaint']);

const GENERATED_HEADER = (/** @type {string} */ what) =>
  `<!-- GENERATED by \`pnpm legal:docs --write\` from ${what}. Do not edit by hand. -->\n\n> **DRAFT — requires counsel review.** Written by a non-lawyer drafting assistant. Not legal advice. Not approved by anyone.\n`;

const VARIANT_LABEL = { EU_FR: 'EU (France)', GB: 'United Kingdom', US: 'United States', SN: 'Senegal', CI: "Côte d'Ivoire", DEFAULT: 'Other / unknown markets' };

/** One generated draft file per in-app legal document: every version, EN and FR, every jurisdiction variant. */
export function draftFiles() {
  /** @type {Record<string, string>} */
  const files = {};
  for (const doc of DEFAULT_REGISTRY.documents) {
    const lines = [GENERATED_HEADER('packages/legal + packages/i18n'), `# ${doc.name} (\`${doc.id}\`)`, ''];
    for (const version of doc.versions) {
      lines.push(`## Version ${version.version}${version.material ? ' (material)' : ''} — published ${version.publishedOn}, effective ${version.effectiveFrom}`, '', `Counsel approval: ${[...new Set(version.approvals.map((a) => a.status))].join(', ')} (see counsel-signoff-tracker.md).`, '');
      for (const locale of /** @type {const} */ (['en', 'fr'])) {
        const t = createTranslator(locale);
        const base = renderDocument(doc, version, locale, 'ZZ');
        lines.push(`### ${locale.toUpperCase()} — ${base.title}`, '', `> ${base.draftBanner}`, '');
        version.sections.forEach((section, i) => {
          if (typeof section === 'string') {
            lines.push(base.sections[i]?.text ?? '', '');
            return;
          }
          lines.push('Jurisdiction-specific section:', '');
          for (const variant of DOCUMENT_VARIANTS) {
            lines.push(`- **${VARIANT_LABEL[variant]}**: ${t.t(resolveSection(section, variant), { minimumAge: 16 })}`);
          }
          lines.push('');
        });
      }
    }
    files[`${LEGAL_DIR}/drafts/${doc.id}.md`] = `${lines.join('\n').trimEnd()}\n`;
  }
  const n = [GENERATED_HEADER('packages/legal/src/notices.ts + packages/i18n'), '# Point-of-risk notices (L3) and AI disclosure (L5)', ''];
  for (const def of NOTICES) {
    n.push(`## \`${def.id}\` v${def.version} — trigger \`${def.trigger}\`, ${def.frequency.replace(/_/g, ' ')}${def.requiresAcknowledgement ? ', acknowledgement required' : ''}`, '');
    for (const locale of /** @type {const} */ (['en', 'fr'])) {
      const r = renderNotice(def, locale, 'ZZ');
      n.push(`- **${locale.toUpperCase()}** — ${r.title}: ${r.body}${r.emergency ? ` ${r.emergency}` : ''}`);
    }
    n.push('');
  }
  n.push('Persistent AI label (every AI coach screen): EN "AI assistant", FR "Assistant IA".', '');
  files[`${LEGAL_DIR}/drafts/point-of-risk-notices.md`] = n.join('\n');
  return files;
}

export const TRACKER_START = '<!-- generated:tracker:start -->';
export const TRACKER_END = '<!-- generated:tracker:end -->';
export const MATRIX_START = '<!-- generated:matrix:start -->';
export const MATRIX_END = '<!-- generated:matrix:end -->';

export function trackerTable() {
  const rows = ['| Text | Version | Jurisdiction variant | Status | Reviewer | Approval record | Date |', '|---|---|---|---|---|---|---|'];
  const row = (/** @type {string} */ text, /** @type {number} */ version, /** @type {import('@fitadapt/legal').CounselApproval} */ a) =>
    rows.push(`| ${text} | ${version} | ${a.variant} | ${a.status} | ${a.status === 'approved' ? a.approvedBy : '—'} | ${a.status === 'approved' ? a.approvalRecord : '—'} | ${a.status === 'approved' ? a.approvedOn : '—'} |`);
  for (const doc of DEFAULT_REGISTRY.documents) for (const v of doc.versions) for (const a of v.approvals) row(`\`${doc.id}\``, v.version, a);
  for (const def of NOTICES) for (const a of def.approvals) row(`notice \`${def.id}\``, def.version, a);
  return rows.join('\n');
}

export function matrixTable() {
  const rows = ['| Code | Market | Text variant | Minimum age | Digital-consent age | Age of majority | Withdrawal | Emergency number | Authority filings (status) | Frameworks to check |', '|---|---|---|---|---|---|---|---|---|---|'];
  const cfg = (/** @type {import('@fitadapt/shared').ConfigValue | null} */ v) => (v ? `${v.value} (validated: ${v.validated})` : 'no known rule');
  for (const p of Object.values(JURISDICTION_MATRIX)) {
    const w = p.withdrawal.periodDays ? `${p.withdrawal.rule}, ${p.withdrawal.periodDays.value} days (validated: false)` : p.withdrawal.rule;
    const filings = p.authorityFilings.length ? p.authorityFilings.map((f) => `${f.authority}: ${f.item} — **${f.status}**`).join('<br>') : 'none identified';
    rows.push(`| ${p.code} | ${p.label} | ${p.variant} | ${cfg(p.ages.minimumAge)} | ${cfg(p.ages.digitalConsentAge)} | ${cfg(p.ages.ageOfMajority)} | ${w} | ${p.emergency.number ?? 'not shown (generic guidance)'} | ${filings} | ${p.frameworks.join('; ')} |`);
  }
  return rows.join('\n');
}

/**
 * @param {string} content
 * @param {string} start
 * @param {string} end
 * @param {string} body
 */
export function replaceBlock(content, start, end, body) {
  const a = content.indexOf(start);
  const b = content.indexOf(end);
  if (a === -1 || b === -1 || b < a) return null;
  return `${content.slice(0, a + start.length)}\n${body}\n${content.slice(b)}`;
}

/**
 * @param {Record<string, string | undefined>} docs repository-relative path -> content (undefined = missing)
 * @returns {string[]} problems
 */
export function checkLegalDocs(docs) {
  const problems = [];
  const generated = draftFiles();
  const all = [...REQUIRED_DOCUMENTS.map((d) => `${LEGAL_DIR}/${d}`), ...Object.keys(generated)];
  for (const path of all) {
    const content = docs[path];
    if (content === undefined) {
      problems.push(`${path}: missing`);
      continue;
    }
    if (!DRAFT_MARKER.test(content)) problems.push(`${path}: not marked "requires counsel review"`);
    if (FORBIDDEN_APPROVAL.test(content)) problems.push(`${path}: claims counsel approval (L5 forbids it)`);
  }
  for (const [path, content] of Object.entries(generated)) {
    if (docs[path] !== undefined && docs[path] !== content) problems.push(`${path}: out of date (run pnpm legal:docs --write)`);
  }

  const founder = docs[`${LEGAL_DIR}/founder-checklist.md`];
  if (founder !== undefined) {
    const rows = tableRows(founder, ['Item', 'Action', 'Status']);
    if (!rows) problems.push('founder-checklist.md: no table with Item, Action, Status');
    else {
      for (const item of GATE0_ITEMS) if (!rows.some((r) => r.Item === item)) problems.push(`founder-checklist.md: Gate 0 item "${item}" missing`);
      for (const r of rows) if (r.Status !== 'open') problems.push(`founder-checklist.md: "${r.Item}" has status "${r.Status}"; only a human with evidence may close a Gate 0 item, and this file starts every item as "open"`);
    }
  }

  const tracker = docs[`${LEGAL_DIR}/counsel-signoff-tracker.md`];
  if (tracker !== undefined) {
    const block = replaceBlock(tracker, TRACKER_START, TRACKER_END, trackerTable());
    if (block === null) problems.push('counsel-signoff-tracker.md: generated block markers missing');
    else if (block !== tracker) problems.push('counsel-signoff-tracker.md: out of date with packages/legal approvals (run pnpm legal:docs --write)');
    const rows = tableRows(tracker, ['Text', 'Jurisdiction variant', 'Status']) ?? [];
    for (const r of rows) if (r.Status !== 'pending' && r.Status !== 'approved') problems.push(`counsel-signoff-tracker.md: ${r.Text} ${r['Jurisdiction variant']} has unknown status "${r.Status}"`);
  }

  const matrix = docs[`${LEGAL_DIR}/jurisdiction-matrix.md`];
  if (matrix !== undefined) {
    const block = replaceBlock(matrix, MATRIX_START, MATRIX_END, matrixTable());
    if (block === null) problems.push('jurisdiction-matrix.md: generated block markers missing');
    else if (block !== matrix) problems.push('jurisdiction-matrix.md: out of date with packages/legal/src/jurisdictions.ts (run pnpm legal:docs --write)');
  }

  const risks = docs[`${LEGAL_DIR}/risk-register.md`];
  if (risks !== undefined) {
    const rows = tableRows(risks, ['Domain', 'Exposure', 'Controls', 'Status']) ?? [];
    for (const d of RISK_DOMAINS) if (!rows.some((r) => r.Domain === d)) problems.push(`risk-register.md: domain "${d}" missing`);
  }

  const list = docs[`${LEGAL_DIR}/document-list.md`];
  if (list !== undefined) {
    const rows = tableRows(list, ['Document', 'Draft', 'Status']) ?? [];
    for (const doc of DEFAULT_REGISTRY.documents) if (!rows.some((r) => (r.Draft ?? '').includes(`drafts/${doc.id}.md`))) problems.push(`document-list.md: no row linking drafts/${doc.id}.md`);
    for (const r of rows) {
      const link = /\(([^)]+\.md)\)/.exec(r.Draft ?? '')?.[1];
      if (!link) problems.push(`document-list.md: "${r.Document}" has no draft link`);
      else if (docs[`${LEGAL_DIR}/${link}`] === undefined && !link.startsWith('../')) problems.push(`document-list.md: "${r.Document}" links a missing draft ${link}`);
      if (!/requires counsel review/i.test(r.Status ?? '')) problems.push(`document-list.md: "${r.Document}" status must say "requires counsel review"`);
    }
  }

  const trademarks = docs[`${LEGAL_DIR}/trademark-register.md`];
  if (trademarks !== undefined) {
    const rows = tableRows(trademarks, ['Mark', 'Role', 'Classes', 'Markets', 'Status']) ?? [];
    const code = rows.find((r) => /fitadapt/i.test(r.Mark ?? ''));
    if (!code) problems.push('trademark-register.md: the codename row is missing');
    else if (!/codename/i.test(code.Role ?? '') || /cleared|registered/i.test(code.Status ?? '')) problems.push('trademark-register.md: the codename must be recorded as a codename, not cleared');
  }

  const incident = docs[`${LEGAL_DIR}/incident-procedure.md`];
  if (incident !== undefined) {
    const headings = incident.split('\n').filter((l) => l.startsWith('#')).map((l) => l.toLowerCase());
    for (const step of INCIDENT_STEPS) if (!headings.some((h) => h.includes(step.toLowerCase()))) problems.push(`incident-procedure.md: no section for "${step}"`);
  }
  return problems;
}
